Entregable N2
wizelineacademy/baz-ios-project-c3-2023 pull request #38
Opened 2023-02-17 18:35 UTC by robertoarzolah

### **Segundo entregable**

_**Se muestra la información de las películas**_

- Se agrego la arquitectura VIPER
- Se crea un UIViewController para mostrar el detalle de las películas
- Crea un buscador de películas
- Se implementa un UICollectionView para los resultados de búsqueda
- Se usaron archivos xibs para generar componentes genéricos
- Se documento e idento el código
_- Quedó pendiente implementar genéricos al consumo de servicios_

2023-02-18 23:19 UTC, EmiMtzV commented on BAZProject/GenericComponents/Cell/MovieCollectionSimilarCell.swift
> +class MovieCollectionSimilarCell: UICollectionViewCell{
Podrías ponerle un nombre mas descriptivo, no sabemos similar a cual celda seria, algo mas como su función

2023-02-18 23:21 UTC, EmiMtzV commented on BAZProject/GenericComponents/HeaderView/HeaderView.swift
> +public class HeaderView: UIView{
La misma sugerencia te diría aquí si va a ser algo genérico ponerle HeaderViewCells o algo que nos mencione que implementa o mueve la headerView

2023-02-18 23:24 UTC, EmiMtzV commented on BAZProject/GenericComponents/HeaderView/HeaderView.swift
> +    private func getDateString() -> String {
podrias ponerlo en un extension de Date para que te retorne la fecha de hoy
RECUERDA: Documentar igual es poner nombres de funciones mas descriptivas `func getTodayDateToString()`

2023-02-18 23:26 UTC, EmiMtzV commented on BAZProject/GenericComponents/MovieConstants.swift
> +    static let titleFilterButton: String = ""
esta constante se esta inicializando vacia podríamos omitirla o cual es el fin de su existencia

2023-02-18 23:28 UTC, EmiMtzV commented on BAZProject/HomeMovies/Entity/Movie.swift
> +enum CellPath {
RECOMENDACION: Podrias moverlo a otro file para que no queden cosas distintas en el mismo File, estas obteniendo una url para la imagen y arriba las urls para las peticiones

2023-02-18 23:33 UTC, EmiMtzV commented on BAZProject/HomeMovies/Interactor/HomeMoviesRemoteDataManager.swift
> +    func getInformationMovie(idMovie id: Int) {
Duda :D Tienes algunas funciones que se utilizan en mas de un dataManager, cual es la razón de esto? lo ideal seria no replicar código, y que exista donde se utiliza

2023-02-18 23:36 UTC, EmiMtzV commented on BAZProject/HomeMovies/Presenter/HomeMoviesPresenter.swift
> +import UIKit
Recuerda que en el Presenter no deberías tener UIKit 👍

2023-02-18 23:49 UTC, EmiMtzV commented on BAZProject/HomeMovies/View/HomeMovies.swift
> +    var searchTerm: String = ""
hay variables que se están inicializando y no se están ocupando, recuerda el manejo de memoria

2023-02-18 23:54 UTC, EmiMtzV commented on BAZProject/HomeMovies/View/HomeMoviesHelper.swift
> +            self.collectionHomeMovie.delegate = self
los delegados y dataSource solo debe asignarse una vez, no cada vez que se hace el reload :D

2023-02-18 23:57 UTC, EmiMtzV commented on BAZProject/InformationMovies/Interactor/InformationMoviesRemoteDataManager.swift
> +        URLSession.shared.dataTask(with: url) { data, response, error in
Observación: podrias hacer una función genérica para esta función que se repite en todas tus. peticiones :D solamente mandándole el modelo, recuerdas lo que habíamos hablado en las mentorias de un networkManager

2023-02-19 00:01 UTC, EmiMtzV commented on BAZProject/InformationMovies/View/InformationMovieViewCollectionProtocolsExtension.swift
> +        return presenter?.getSimilarMoviesCount() ?? 0
aqui si te fijas repites dos veces `presenter?.getSimilarMoviesCount() ?? 0` podrias cambiarlo por 
`guard let numberOfSimiliarMovies = presenter?.getSimilarMoviesCount() else { return 0 }
return numberOfSimiliarMovies > 6 ? 6 : numberOfSimiliarMovies
`

2023-02-19 00:03 UTC, EmiMtzV commented on BAZProject/InformationMovies/View/InformationMovieViewCollectionProtocolsExtension.swift
> +        cell.setupCell(movie: self.presenter?.getSimilarMovie(indexPathRow: indexPath.row) ?? Movie())
ya que estas agregando tu cell a un Guard let podrias meter igual la validación de tu row en el mismo 
`guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: MovieCollectionSimilarCell.cellIdentifier, for: indexPath) as? MovieCollectionSimilarCell,
let row = self.presenter?.getSimilarMovie(indexPathRow: indexPath.row) else { return .....`

2023-02-19 00:05 UTC, EmiMtzV commented on BAZProject/InformationMovies/View/InformationMoviesHelper.swift
> +            self.collectionMovieSimilar.delegate = self
lo mismo aqui no asignes los delegados mas de una vez, esto debería estar en tu init de tu 'InformationMoviesView'

2023-02-19 00:06 UTC, EmiMtzV commented on BAZProject/InformationMovies/View/InformationMoviesHelper.swift
> +                let alert = UIAlertController(title: Constants.errorAlertResult, message: message, preferredStyle: .alert)
aqui solo una sugerencia, tal vez podrias armar un builder de la alerta para solo mandarle los parámetros que mas cambien, el mensaje y el titulo

2023-02-19 00:08 UTC, EmiMtzV commented on BAZProject/InformationMovies/View/InformationMoviesView.swift
> +        self.labelDetail.text = "\(presenter?.informationMovieData?.originalTitle ?? "") | \(presenter?.informationMovieData?.genres?.first?.name ?? "") | \(presenter?.informationMovieData?.releaseDa
dos comentarios, la linea es demasiado larga, podrias ver una solución que la haga mas legible, y cuando pongas ternarios para el else respeta el espacio 18+":

2023-02-20 16:13 UTC, robertoarzolah commented on BAZProject/HomeMovies/View/HomeMovies.swift
> +    var searchTerm: String = ""
Sí se usan, pero no en esa clase. Estas me ayudan a hacer búsquedas en el collection y search extension

2023-02-20 17:15 UTC, robertoarzolah commented on BAZProject/InformationMovies/Interactor/InformationMoviesRemoteDataManager.swift
> +        URLSession.shared.dataTask(with: url) { data, response, error in
En mi siguiente versión tratare de implementar los genéricos para los servicios; en esta versión fue complicado hacer los ajustes

2023-02-21 21:03 UTC, EmiMtzV approved these changes

2023-02-21 21:06 UTC, EmiMtzV requested changes

2023-02-21 21:12 UTC, EmiMtzV approved these changes

2023-02-21 21:12 UTC, merged