Dev hugo lechuga
wizelineacademy/baz-ios-project-c3-2023 pull request #71
Opened 2023-03-02 15:21 UTC by bazhalc18

Entregable final con mejoras propuestas por Alejandro .

Enum para cargar el detalle de la película
Notification Center

2023-03-03 21:14 UTC, alejandrombWize commented on BAZProject/ListMovies/ListMoviesTableViewCell /MovieTableViewCell.swift
> +extension MovieTableViewCell : UICollectionViewDataSource {
No usar force unwrapping en esta clase.

2023-03-03 21:15 UTC, alejandrombWize commented on BAZProject/ListMovies/ListMoviesTableViewCell /MovieTableViewCell.swift
> +        return CGSize(width: 150, height: 250)
Añadir este Size al inicio de la clase.

2023-03-03 21:23 UTC, alejandrombWize commented on BAZProject/ListMovies/ListMoviesView.swift
> +        lblViewedMovies.text = "Visitas \n\(UserDefaults.standard.integer(forKey: "contador"))"
Usar strings localizables

2023-03-03 21:25 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                do{
```suggestion
                do {
```

2023-03-03 21:25 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                }catch let decodingError as DecodingError {
```suggestion
                } catch let decodingError as DecodingError {
```

2023-03-03 21:26 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                    case .typeMismatch(_, let c), .valueNotFound(_, let c), .keyNotFound(_, let c), .dataCorrupted(let c):
¿Que significa c?

2023-03-03 21:26 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                do{
```suggestion
                do {
```

2023-03-03 21:26 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                }catch let decodingError as DecodingError {
```suggestion
                } catch let decodingError as DecodingError {
```

2023-03-03 21:26 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                    case .typeMismatch(_, let c), .valueNotFound(_, let c), .keyNotFound(_, let c), .dataCorrupted(let c):
Nombramiento

2023-03-03 21:26 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                do{
```suggestion
                do {
```

2023-03-03 21:27 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                }catch let decodingError as DecodingError {
```suggestion
                } catch let decodingError as DecodingError {
```

2023-03-03 21:27 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                    case .typeMismatch(_, let c), .valueNotFound(_, let c), .keyNotFound(_, let c), .dataCorrupted(let c):
Nombramiento

2023-03-03 21:27 UTC, alejandrombWize commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                    debugPrint(error.localizedDescription )
```suggestion
                    debugPrint(error.localizedDescription)
```

2023-03-03 21:29 UTC, alejandrombWize commented on BAZProject/MovieDetail/Views/Cast/CastTableViewCell.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: CastCollectionViewCell.identifier, for: indexPath) as? CastCollectionViewCell else { return UICollectionViewCell() }
Linea de código demasiado larga.

2023-03-03 21:30 UTC, alejandrombWize commented on BAZProject/MovieDetail/Views/SimilarMovies/SimilarMovieTableViewCell/SimilarMovieTableViewCell.swift
> +        guard let cell: SimilarMovieCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: SimilarMovieCollectionViewCell.identifier, for: indexPath) as? SimilarMovieCollectionV
Code smell: Linea de código demasiado larga.

2023-03-03 21:36 UTC, alejandrombWize requested changes
La app funciona correctamente con algunos detalles, en Home; algunas películas no mantienen un poster por default y en Detalle de Película, algunas películas muestran valores vacíos. Asimismo se detectaron referencias cíclicas en un par de módulos.

En cuanto al código, tiene algunos code smells menores; algún force unwrapping, y detalles sencillos de resolver.

2023-03-03 21:37 UTC, alejandrombWize commented
Hay referencias cruzadas, que generan fugas de memoria.

![Screen Shot 2023-03-03 at 15 22 56](https://user-images.githubusercontent.com/110190478/222833980-9ef27a93-864f-474e-aaa4-d7b476044802.png)

2023-03-03 21:40 UTC, alejandrombWize commented
Algunas películas no poseen un poster por default y en detalle de película no muestran información u alguna nota que notifique al usuario que no hay información al respecto.

![Simulator Screen Shot - iPhone 14 - 2023-03-03 at 15 33 02](https://user-images.githubusercontent.com/110190478/222834093-f2082d96-5ca6-48e3-be0b-a0c858ab69cd.png)
![Simulator Screen Shot - iPhone 14 - 2023-03-03 at 15 33 05](https://user-images.githubusercontent.com/110190478/222834115-fbfd591e-cc54-477b-a777-7927ae13c5de.png)

2023-03-03 23:41 UTC, bazhalc18 commented on BAZProject/ListMovies/ListMoviesTableViewCell /MovieTableViewCell.swift
> +extension MovieTableViewCell : UICollectionViewDataSource {
Corregido

2023-03-03 23:43 UTC, bazhalc18 commented on BAZProject/ListMovies/ListMoviesTableViewCell /MovieTableViewCell.swift
> +        return CGSize(width: 150, height: 250)
Listo

2023-03-04 00:04 UTC, bazhalc18 commented on BAZProject/ListMovies/ListMoviesView.swift
> +        lblViewedMovies.text = "Visitas \n\(UserDefaults.standard.integer(forKey: "contador"))"
No estpy muy seguro de esto pero te refieres a poner con triple comilla ? 
Ejem:
"""vistas
\(valiable)
"""

2023-03-04 00:05 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                }catch let decodingError as DecodingError {
Listo

2023-03-04 00:05 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                    case .typeMismatch(_, let c), .valueNotFound(_, let c), .keyNotFound(_, let c), .dataCorrupted(let c):
Listo es el contexto para cachar el error

2023-03-04 00:06 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                do{
Listo

2023-03-04 00:07 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                }catch let decodingError as DecodingError {
Listo

2023-03-04 00:07 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                    case .typeMismatch(_, let c), .valueNotFound(_, let c), .keyNotFound(_, let c), .dataCorrupted(let c):
Listo

2023-03-04 00:07 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                do{
Listo

2023-03-04 00:07 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                }catch let decodingError as DecodingError {
Listo

2023-03-04 00:07 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                    case .typeMismatch(_, let c), .valueNotFound(_, let c), .keyNotFound(_, let c), .dataCorrupted(let c):
Listo

2023-03-04 00:11 UTC, bazhalc18 commented on BAZProject/MovieDetail/MovieDetailInteractor.swift
> +                    debugPrint(error.localizedDescription )
Listo

2023-03-04 00:14 UTC, bazhalc18 commented on BAZProject/MovieDetail/Views/Cast/CastTableViewCell.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: CastCollectionViewCell.identifier, for: indexPath) as? CastCollectionViewCell else { return UICollectionViewCell() }
Listo

2023-03-04 00:16 UTC, bazhalc18 commented on BAZProject/MovieDetail/Views/SimilarMovies/SimilarMovieTableViewCell/SimilarMovieTableViewCell.swift
> +        guard let cell: SimilarMovieCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: SimilarMovieCollectionViewCell.identifier, for: indexPath) as? SimilarMovieCollectionV
Listo

2023-03-06 21:03 UTC, alejandrombWize commented on BAZProject/ListMovies/ListMoviesView.swift
> +        lblViewedMovies.text = "Visitas \n\(UserDefaults.standard.integer(forKey: "contador"))"
Me refiero para que en un futuro tenga soporte a otros idiomas: https://developer.apple.com/documentation/xcode/localization

2023-03-06 21:05 UTC, alejandrombWize approved these changes
Se atendieron los comentarios hechos por el mentor 👍

2023-03-06 21:05 UTC, merged