Primera entrega
wizelineacademy/baz-ios-project-c3-2023 pull request #9
Opened 2023-02-02 19:55 UTC by luis-v04

2023-02-03 20:26 UTC, mtorres0 commented on BAZProject/Extensions/StringExtension.swift
> +    func convertDate(format: String, with newFormat: String) -> String? {
Me suena un poco mejor está definición de este método.
`func convertDate(from format: String, to newFormat: String)`

2023-02-03 20:49 UTC, mtorres0 requested changes

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/Extensions/StringExtension.swift
> +    func convertDate(format: String, with newFormat: String) -> String? {
No me hace sentido que cambies una fecha que se encuentra en un `String` y devuelvas otro `String`. ¿Es por que lo quieres presentar en otro formato en un label?

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/Models/Movie.swift
> +    private let posterPath: String
¿Por qué estos parámetros son privados?. Yo pienso que serían más utiles si fueran internal.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/MovieList/MovieCell/MovieTableViewCell.swift
> +class MovieTableViewCell: UITableViewCell {
Agregar `final` a esta clase.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/MovieList/MovieCell/MovieTableViewCell.swift
> +    static let nib: UINib = UINib(nibName: "MovieTableViewCell", bundle: .main)
Para no escribir el nombre de la clase y cometer errores puedes ponerlo con esto  `String(describing: self)` y debería darte el nombre de la clase.
`static let nib: UINib = UINib(nibName: String(describing: self), bundle: .main)`

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/MovieList/MovieProvider.swift
> +    private func getMoviesRequest() -> URLRequest? {
Hace falta documentar este método.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/TrendingViewController.swift
>  class TrendingViewController: UITableViewController {
Agregar `final`.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/TrendingViewController.swift
> +        movieAPI.getMovies { (result: Result<[Movie], Error>) in
Es importante usar `[weak self]` ya que este es un escaping clousure y además sí estás usando self dentro del cuerpo.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/TrendingViewController.swift
> +                self.tableView.reloadData()
Es recomentable que el `realoadData` se haga en el main thread.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/TrendingViewController.swift
> +    private func setTable() {
Podríamos cambiar el nombre del método por `setupTable()`, sería un poco más descriptivo.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/TrendingViewController.swift
> +    private func setMovies() {
También podríamos cambiar el nombre de este método. Algo como `requestMovies` o algo que describa mejor lo que realiza, creo que `setMovies` no lo describe bien del todo.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/MovieList/MovieProvider.swift
> +    func set(_ cell: UITableViewCell, with movie: Movie) {
Creo que es mejor que se asignen los valores de la celda dentro de la misma celda. Que la celda reciba el modelo y lo asigne a donde corresponde. Esta clase no debería saber nada de la vista ni tener referencias a ella, solo debería importar `Foundation` y no `UIKit`.

2023-02-03 20:49 UTC, mtorres0 commented on BAZProject/MovieList/MovieCell/MovieTableViewCell.swift
> +
Aquí podrías poner un método que reciba el modelo `Movie` como parámetro para poder llenar los elementos de la vista.

2023-02-03 21:24 UTC, luis-v04 commented on BAZProject/Models/Movie.swift
> +    private let posterPath: String
estos parámetros son privados porque se sustituyen por otras propiedades o métodos, dejarlos causaría confusión

2023-02-03 22:46 UTC, luis-v04 commented on BAZProject/TrendingViewController.swift
> +                self.tableView.reloadData()
este método ya te responde sobre el hilo principal por eso ya no lo incluí en esta parte

2023-02-07 04:31 UTC, mtorres0 requested changes

2023-02-07 04:31 UTC, mtorres0 commented on BAZProject/Utilities/MovieCategory.swift
> +    private func getBaseURL(for page: Int) -> URL? {
Falta la documentación de este método.

2023-02-07 04:31 UTC, mtorres0 commented on BAZProject/Models/Movie.swift
> +    private let posterPath: String
ok

2023-02-07 04:31 UTC, mtorres0 commented on BAZProject/MovieList/MovieCell/MovieTableViewCell.swift
> +        DispatchQueue.global(qos: .utility).async {
aquí no le veo el caso de usar un `DispatchQueue`, el `task` de abajo ya es asincrono.

2023-02-08 15:38 UTC, mtorres0 approved these changes

2023-02-08 15:38 UTC, merged